management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
  datasource:
    testWhileIdle: 'true'
    driver-class-name: org.postgresql.Driver
    validationQuery: SELECT 1
    username: postgres
    url: jdbc:postgresql://localhost:5432/ostock_dev
    password: postgres
  application:
    name: licensing-service
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
