server:
  port: 8072

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: organization-service
          uri: lb://ORGANIZATION-SERVICE
          predicates:
            - Path=/v1/organization/**
  session:
    store-type: redis
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

